from __future__ import annotations
import ryupy
__all__ = ['tensor']
class tensor(ryupy._ITensor):
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __add__(self, arg0: tensor) -> tensor:
        ...
    def __init__(self, arg0: int) -> None:
        ...
    def print_info(self) -> None:
        ...
    @property
    def data(self) -> list:
        ...
    @property
    def size(self) -> int:
        ...
